server:
  port: 8702 # 端口自己决定# 指定当前eureka客户端的注册地址，也就是eureka服务的提供方，当前配置的服务的注册服务方
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8700/eureka,http://windows10.microdone.cn:8703/eureka
    register-with-eureka: true #自身 不在向eureka注册
    fetch-registry: true #启动时禁用client的注册
  instance:
    hostname: localhost #指定应用名称
spring:
  application:
    name: udd
  redis:
    port: 6379
    host: 127.0.0.1
    minIdle: 100
    timeout: 30000
    testOnBorrow: true
    password: 123456
  datasource:
    #数据库驱动
    #      driverClassName: org.postgresql.Driver
    driverClassName: com.mysql.jdbc.Driver
    #数据库连接
    #      url: jdbc:postgresql://localhost:5432/biyi_base
    url: jdbc:mysql://localhost:3306/spring-cloud-demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowMultiQueries=true&noAccessToProcedureBodies=true
    #数据库的名称,biyi-form组件使用
    db-name: spring-cloud-demo

    #数据库连接池
    #    type: com.zaxxer.hikari.HikariDataSource
    #数据库用户名
    username: root
    #数据库密码
    password: 123456
    hikari:
      #最大连接池数
      maximumPoolSize: 20
    #是否自定义配置
    cachePrepStmts: true
    #连接池大小
    prepStmtCacheSize: 250
    #单条语句最大长度
    prepStmtCacheSqlLimit: 2048
    #新版本MySQL支持服务器端准备，是否开启
    useServerPrepStmts: true

#开启feign的压缩功能
feign:
  compression:
    request:
      enabled: true
      #支持的媒体类型列表
      mime-types: text/xml,application/xml,application/json
      #请求的最小阈值
      min-request-size: 2048
    response:
      enabled: true

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30